version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: motemesse-postgres
    restart: always
    environment:
      POSTGRES_DB: motemesse
      POSTGRES_USER: motemesse_user
      POSTGRES_PASSWORD: motemesse_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U motemesse_user']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: